# Generated by Django 4.0.4 on 2022-05-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Mobile', models.IntegerField(max_length=11)),
                ('Email', models.EmailField(max_length=50)),
                ('Gender', models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other'), ('4', 'Prefer Not Say')], default='---', max_length=50)),
                ('Student_Number', models.IntegerField(blank=True, null=True, unique=True)),
                ('Path', models.CharField(choices=[('0', '--------'), ('1', 'Full Stack'), ('2', 'AWS-DevOps'), ('3', 'Data Science'), ('4', 'Cyber Security')], default='0', max_length=50)),
            ],
        ),
    ]
