# Generated by Django 4.0.4 on 2022-05-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0002_alter_student_mobile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Mobile',
        ),
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(choices=[('1', 'Female'), ('2', 'Male'), ('3', 'Other'), ('4', 'Prefer Not Say')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='Path',
            field=models.CharField(choices=[('1', 'Full Stack'), ('2', 'AWS-DevOps'), ('3', 'Data Science'), ('4', 'Cyber Security')], max_length=50),
        ),
    ]
